name: withtalk_mobile
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_bloc: ^8.1.1
  # primary loading view
  # flutter_spinkit: ^5.1.0
  easy_localization: ^3.0.1
  # local data base
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.4.0
  lottie: ^1.4.2
  page_transition: ^2.0.9
  flutter_masked_text2: ^0.9.1
  # pin_code_fields: ^7.4.0
  motion_toast: ^2.4.3
  connectivity_plus: ^2.3.9
  retrofit: ^3.3.1
  dio: ^4.0.6
  logger: ^1.1.0
  smooth_page_indicator: ^1.0.0+2
  # http: ^0.13.4
  flutter_keyboard_visibility: ^5.4.0
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  flutter_rating_bar: ^4.0.1
  package_info_plus: ^3.0.1
  image_picker: ^0.8.6
  # url_launcher: ^6.1.6
  http_parser: ^4.0.2
  # map_launcher: ^2.4.0
  # flutter_svg: ^1.1.6
  # location: ^4.4.0
  # video_player: ^2.4.10
  firebase_core: ^2.4.1
  cloud_firestore: ^4.0.4
  firebase_messaging: ^14.2.1
  awesome_notifications: ^0.7.4+1
  badges: ^2.0.3
  like_button: ^2.0.5
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  json_serializable: ^6.4.1
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.2
  flutter_native_splash: ^2.2.16


flutter:

  uses-material-design: true


  assets:
    - lib/data/local_sources/localization/
    - assets/icons/
    - assets/images/
    - assets/lotties/
      


